### ISSUE TITLE
ssStart und ssEnd-Marker sind in der Resultatliste zu sehen (?)

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/brahms_static#15]
## Aktuelles Verhalten

* Auf [Datenbanksuche](https://acdh-oeaw.github.io/brahms_static/search.html)
* öffne "Erweiterte Suche"
* Suchfeld "001 Werk": "op. 8" eingeben und in der Autocomplete-Liste den Eintrag "Klaviertrio Nr1. H-Dur, op. 8" auswählen
* Klick auf "Suche" 
* Die [Suchresultatliste](https://acdh-oeaw.github.io/brahms_static/search.html?002%20Werk=Klaviertrio%20Nr.%201%20H-Dur,%20op.%208) wird angezeigt, allerdings werden Texteile, die als Fettdruck bzw. kursiviert dargestellt werden sollen, nicht richig gerendert, sondern Start- und End-Markierungen "ssStart" und "ssEnd" verbatim wiedergegeben.

![image](https://user-images.githubusercontent.com/4641281/178077764-40d74b43-17f6-429e-b192-ee898d37373f.png)

## Erwartetes Verhalten:

Die Suchresultatliste wird korrekt mit Hervorhebungen gerendert, d.h. die start- und Endtags sind nicht sichtbar.

**@brahms-online Bitte kontrollieren:** In einem aktuellen Windows 10 ist das unter 'Aktuelles Verhalten' beschriebene Problem nicht nachollziehbar. (weder in Google Chrome Version 96.0.4664.45, Firefox 102.0 (64-bit) noch in Microsoft Edge Version 103.0.1264.49 (64-bit)). Dort sieht das Ergebnis korrekt aus (wobei die Start/End-Markierungen für einen Sekundenbruchteil zu sehen sind bis sie durch das entsprechende HTML/CSS Markup ersetzt werden.)

![image](https://user-images.githubusercontent.com/4641281/178079917-0944fa3c-0693-4809-9f7d-60a7f054f999.png)

**Comment by linxOD** [comment]
https://github.com/acdh-oeaw/brahms_static/commit/f80b7b683c2269dfd110b1703556552da391ea32#diff-4a2942ec61d7f35fc08a1d508cce685f33827f5a0c2aa29d1e35480c23a21e2eR354

**Comment by linxOD** [comment]
should be fixed

**Comment by linxOD** [comment]
@brahms-online , @BrahmsOnline
can you test and if it works as requested please close the issue.

**Comment by BrahmsOnline** [comment]
yes, it looks as if it's fixed
